# Generated by Django 4.1.7 on 2023-03-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0002_remove_graffiti_x_coordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graffiti',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graffiti',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Helvetica', 'Helvetica'), ('Another', 'Another')], max_length=30),
        ),
        migrations.AlterField(
            model_name='graffiti',
            name='location_x',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='graffiti',
            name='location_y',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
