# Generated by Django 4.1.7 on 2023-03-25 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0006_alter_graffiti_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graffiti',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
