# Generated by Django 4.1.7 on 2023-03-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graffiti',
            name='x_coordinate',
        ),
        migrations.RemoveField(
            model_name='graffiti',
            name='y_coordinate',
        ),
        migrations.AddField(
            model_name='graffiti',
            name='location_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graffiti',
            name='location_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='graffiti',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Helvetica', 'Helvetica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='graffiti',
            name='text',
            field=models.CharField(max_length=280),
        ),
    ]
