# Generated by Django 4.1.7 on 2023-03-25 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0003_graffiti_color_alter_graffiti_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graffiti',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 22, 21, 51, 144380)),
        ),
        migrations.AlterField(
            model_name='graffiti',
            name='font',
            field=models.CharField(choices=[('Roboto', 'Default'), ('Creepster', 'Creepy'), ('Monoton', 'Vinyl'), ('Rye', 'Wildwest'), ('Henny Penny', 'Circus'), ('Emilys Candy', 'Love'), ('Bungee Shade', 'Shade3D'), ('Another', 'Graffiti'), ('Gruppo', 'Minimalistic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='graffiti',
            name='text',
            field=models.CharField(max_length=64),
        ),
    ]
