# Generated by Django 4.1.7 on 2023-03-25 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0005_alter_graffiti_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graffiti',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 22, 24, 11, 517104, tzinfo=datetime.timezone.utc)),
        ),
    ]
