# Generated by Django 4.1.7 on 2023-04-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0007_alter_graffiti_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='graffiti',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
