# Generated by Django 4.1.7 on 2023-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image_link', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=360)),
                ('links', models.CharField(max_length=100)),
            ],
        ),
    ]
