# Generated by Django 4.1.7 on 2023-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='techlink',
            name='name',
            field=models.CharField(default='a', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=' your email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1024, verbose_name=' message'),
        ),
    ]
