# Generated by Django 4.1.7 on 2023-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_techlink_name_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techlink',
            name='project',
        ),
        migrations.AddField(
            model_name='techlink',
            name='project',
            field=models.ManyToManyField(to='main.project'),
        ),
    ]
