# Generated by Django 4.1.7 on 2023-04-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_techlink_project_project_tech_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techlink',
            name='icon',
            field=models.CharField(max_length=360),
        ),
    ]
