# Generated by Django 4.1.7 on 2023-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_techlink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techlink',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
    ]
